# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.25.0"

default_platform :ios

platform :ios do

  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    ENV['CRASHLYTICS_API_TOKEN'] = "f083510bfa8fefe2571d830145eb808945803383"
    ENV['CRASHLYTICS_BUILD_SECRET'] = "ff1bb2c3773f866b1dd8eac22c45f69c3f564122960d009c1e5881ab2e58cec4"
  end

  desc "Submit a new Beta Build to Apple Crashlytics"
  lane :beta do

    cert

    gym(
      workspace: "circleci.xcworkspace",
      configuration: "Release",
      scheme: "circleci",
      clean: true
    )

    crashlytics(
      crashlytics_path: "Pods/Crashlytics/iOS/Crashlytics.framework", # path to your Crashlytics.framework
      groups: ["Testers"],
      notifications: true
    )

    # You can also use other beta testing services here (run `fastlane actions`)
    slack(
      message: "Successfully deployed new Crashlytics Beta update.",
    )

  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    # gym # Build your app - more options available
    # deliver(force: true)
    # frameit
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
